### ISSUE TITLE
Keyboard shortcut doesn't work in Windows

### ISSUE THREAD

**Issue by abogawat** [jugyo/SublimeSuperNavigator#1]
I love the way the plugin works when called from the command palette. Problem is, the default shortcut doesn't seem to work on Windows (I'm using 8, but I don't think it is specific to Win 8 only).

Is there a way to customize the key binding? I can't find any way to set custom preferences for the package.

**Comment by abogawat** [comment]
You know what, I just figured it out. Added the following in the "Key Bindings - User" file, in case anybody wants to know:

{
    "keys": ["ctrl+k", "ctrl+a"],
    "command": "super_navigate"
}

**Comment by jugyo** [comment]
Ah, I see. Thank you for letting me know.

**Comment by MarkGoldberg** [comment]
Sorry, I missed the closed issue before sending the pull request with the fix
